[features]
seeds = false
skip-lint = false
[programs.devnet]
data_feed_dapp = "BNK1JjB9vENSrinH4RJbSnLCJQrS9h1Mf21A4VjUh2a7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/anoy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
